"""
Builds backend/data/recipes_full.json — a real recipe dataset (proper dish
names, ingredients, steps, nutrition, etc.) to replace the old cuisine
classification dataset (cuisine_data.csv / recipes_index.json), which only
had cuisine labels ("french", "spanish") as recipe names.

Run: venv/Scripts/python.exe scripts/generate_recipes.py
"""

import json
import os

RECIPES = [
    {
        "name": "Scrambled Eggs",
        "ingredients": ["egg", "milk", "butter", "salt"],
        "steps": [
            "Crack eggs into a bowl",
            "Add milk and whisk together",
            "Melt butter in a pan over medium heat",
            "Pour egg mixture in and stir gently",
            "Season with salt and serve",
        ],
        "prep_time": "5 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 220, "protein": "14g", "carbs": "2g", "fat": "17g"},
        "sustainability_tip": "Use leftover egg shells as plant fertilizer",
        "diet_tags": ["Vegetarian", "Healthy"],
        "cuisine": "Western",
    },
    {
        "name": "Spinach & Egg Omelette",
        "ingredients": ["spinach", "egg", "olive oil", "garlic", "salt"],
        "steps": [
            "Whisk eggs with a pinch of salt",
            "Heat olive oil and saute garlic until fragrant",
            "Add spinach and cook until wilted",
            "Pour eggs over the spinach and cook on low heat until set",
            "Fold the omelette in half and serve warm",
        ],
        "prep_time": "10 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 280, "protein": "18g", "carbs": "4g", "fat": "20g"},
        "sustainability_tip": "Spinach stems are edible — chop and cook them too instead of discarding",
        "diet_tags": ["Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Tomato Basil Pasta",
        "ingredients": ["pasta", "tomato", "basil", "garlic", "olive oil"],
        "steps": [
            "Boil pasta in salted water until al dente",
            "Saute garlic in olive oil until golden",
            "Add chopped tomatoes and simmer into a sauce",
            "Toss the drained pasta into the sauce",
            "Stir in fresh basil off the heat and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 410, "protein": "12g", "carbs": "68g", "fat": "10g"},
        "sustainability_tip": "Overripe tomatoes work great here — don't throw them out",
        "diet_tags": ["Vegan", "Vegetarian"],
        "cuisine": "Italian",
    },
    {
        "name": "Chicken Stir Fry",
        "ingredients": ["chicken breast", "bell pepper", "soy sauce", "garlic", "onion"],
        "steps": [
            "Slice chicken breast into thin strips",
            "Heat oil in a wok over high heat",
            "Stir-fry chicken until browned",
            "Add bell pepper, onion and garlic, stir-fry 2 minutes",
            "Pour in soy sauce, toss to coat and serve hot",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 390, "protein": "34g", "carbs": "18g", "fat": "16g"},
        "sustainability_tip": "Save chicken bones and vegetable scraps for a homemade stock",
        "diet_tags": ["High Protein", "Halal"],
        "cuisine": "Asian",
    },
    {
        "name": "Green Smoothie Bowl",
        "ingredients": ["spinach", "banana", "milk", "honey"],
        "steps": [
            "Blend spinach, banana, milk and honey until smooth",
            "Pour into a bowl",
            "Top with your favourite fruit and seeds",
            "Serve immediately",
        ],
        "prep_time": "10 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 240, "protein": "6g", "carbs": "45g", "fat": "3g"},
        "sustainability_tip": "Freeze overripe bananas instead of tossing them",
        "diet_tags": ["Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Vegetable Fried Rice",
        "ingredients": ["rice", "carrot", "egg", "soy sauce", "onion", "garlic"],
        "steps": [
            "Cook rice and let it cool (day-old rice works best)",
            "Scramble the egg in a hot wok and set aside",
            "Saute garlic and onion until fragrant",
            "Add carrot and stir-fry until tender",
            "Add rice, soy sauce and egg, stir-fry until combined",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 360, "protein": "10g", "carbs": "58g", "fat": "9g"},
        "sustainability_tip": "Use leftover rice and vegetable odds and ends to avoid waste",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Asian",
    },
    {
        "name": "Chicken Fried Rice",
        "ingredients": ["rice", "chicken breast", "egg", "soy sauce", "onion", "garlic"],
        "steps": [
            "Dice and cook chicken breast until golden, set aside",
            "Scramble the egg and set aside",
            "Saute garlic and onion in the same pan",
            "Add cooked rice and break up any clumps",
            "Return chicken and egg to the pan, add soy sauce and toss together",
        ],
        "prep_time": "15 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 430, "protein": "28g", "carbs": "52g", "fat": "12g"},
        "sustainability_tip": "This is a great way to use up leftover rice and cooked chicken",
        "diet_tags": ["High Protein", "Halal"],
        "cuisine": "Asian",
    },
    {
        "name": "Garlic Butter Shrimp",
        "ingredients": ["shrimp", "butter", "garlic", "lemon", "parsley"],
        "steps": [
            "Pat shrimp dry and season with salt",
            "Melt butter in a pan over medium heat",
            "Add garlic and cook until fragrant",
            "Add shrimp and cook 2 minutes per side until pink",
            "Squeeze lemon juice over the top and garnish with parsley",
        ],
        "prep_time": "10 min",
        "cook_time": "8 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "24g", "carbs": "3g", "fat": "17g"},
        "sustainability_tip": "Keep shrimp shells to make a quick seafood stock",
        "diet_tags": ["Gluten-Free", "Pescatarian"],
        "cuisine": "Western",
    },
    {
        "name": "Beef Tacos",
        "ingredients": ["ground beef", "tortilla", "onion", "tomato", "cheese", "lettuce"],
        "steps": [
            "Brown the ground beef with diced onion",
            "Season with cumin, paprika and salt",
            "Warm the tortillas in a dry pan",
            "Fill tortillas with beef, tomato, cheese and lettuce",
            "Serve with lime wedges",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 420, "protein": "26g", "carbs": "30g", "fat": "22g"},
        "sustainability_tip": "Use vegetable trimmings from onion and tomato in a stock bag in the freezer",
        "diet_tags": ["High Protein"],
        "cuisine": "Mexican",
    },
    {
        "name": "Chicken Caesar Salad",
        "ingredients": ["chicken breast", "lettuce", "parmesan", "bread", "olive oil"],
        "steps": [
            "Grill or pan-sear the chicken breast until cooked through, then slice",
            "Cube bread and toast in olive oil to make croutons",
            "Toss lettuce with caesar dressing",
            "Top with chicken, croutons and shaved parmesan",
            "Serve immediately",
        ],
        "prep_time": "15 min",
        "cook_time": "15 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 410, "protein": "32g", "carbs": "20g", "fat": "22g"},
        "sustainability_tip": "Stale bread makes the best croutons — don't throw it out",
        "diet_tags": ["High Protein", "Halal"],
        "cuisine": "Western",
    },
    {
        "name": "Margherita Pizza",
        "ingredients": ["flour", "tomato", "mozzarella", "basil", "olive oil"],
        "steps": [
            "Roll out the pizza dough on a floured surface",
            "Spread a thin layer of crushed tomato sauce",
            "Top with torn mozzarella",
            "Bake at high heat until the crust is golden and cheese bubbles",
            "Finish with fresh basil and a drizzle of olive oil",
        ],
        "prep_time": "20 min",
        "cook_time": "12 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 520, "protein": "20g", "carbs": "62g", "fat": "20g"},
        "sustainability_tip": "Freeze extra dough portions instead of making a whole batch at once",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Italian",
    },
    {
        "name": "Creamy Mushroom Risotto",
        "ingredients": ["rice", "mushroom", "onion", "garlic", "parmesan", "butter"],
        "steps": [
            "Saute onion and garlic in butter until soft",
            "Add sliced mushrooms and cook until browned",
            "Stir in rice and toast for a minute",
            "Add warm stock a ladle at a time, stirring until absorbed",
            "Finish with parmesan and a knob of butter",
        ],
        "prep_time": "10 min",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 440, "protein": "12g", "carbs": "60g", "fat": "16g"},
        "sustainability_tip": "Mushroom stems and trimmings can go straight into the stock pot",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Italian",
    },
    {
        "name": "Baked Salmon with Vegetables",
        "ingredients": ["salmon", "broccoli", "carrot", "olive oil", "lemon"],
        "steps": [
            "Preheat the oven to 200C",
            "Place salmon and chopped vegetables on a tray",
            "Drizzle with olive oil, salt and pepper",
            "Bake for 15-18 minutes until salmon flakes easily",
            "Squeeze lemon over the top before serving",
        ],
        "prep_time": "10 min",
        "cook_time": "18 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 380, "protein": "34g", "carbs": "14g", "fat": "21g"},
        "sustainability_tip": "Save the lemon peel to make citrus-infused water or zest for baking",
        "diet_tags": ["Pescatarian", "Gluten-Free", "Healthy"],
        "cuisine": "Western",
    },
    {
        "name": "Chicken Noodle Soup",
        "ingredients": ["chicken breast", "noodles", "carrot", "onion", "garlic"],
        "steps": [
            "Saute onion, garlic and carrot until fragrant",
            "Add chicken and stock, bring to a simmer",
            "Cook until chicken is tender, then shred it",
            "Add noodles and cook until tender",
            "Season with salt and pepper and serve hot",
        ],
        "prep_time": "10 min",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 320, "protein": "24g", "carbs": "34g", "fat": "8g"},
        "sustainability_tip": "Use the chicken carcass to make stock instead of buying it",
        "diet_tags": ["Halal"],
        "cuisine": "Western",
    },
    {
        "name": "Tomato Soup",
        "ingredients": ["tomato", "onion", "garlic", "butter", "milk"],
        "steps": [
            "Saute onion and garlic in butter until soft",
            "Add chopped tomatoes and simmer for 15 minutes",
            "Blend until smooth",
            "Stir in a splash of milk for creaminess",
            "Season and serve with crusty bread",
        ],
        "prep_time": "10 min",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 210, "protein": "5g", "carbs": "24g", "fat": "10g"},
        "sustainability_tip": "Overripe or blemished tomatoes are perfect for soup",
        "diet_tags": ["Vegetarian", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Grilled Cheese Sandwich",
        "ingredients": ["bread", "cheese", "butter"],
        "steps": [
            "Butter one side of each slice of bread",
            "Place cheese between the slices, buttered sides out",
            "Grill in a pan over medium heat until golden",
            "Flip and cook the other side until cheese melts",
            "Slice and serve warm",
        ],
        "prep_time": "5 min",
        "cook_time": "8 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 400, "protein": "16g", "carbs": "32g", "fat": "24g"},
        "sustainability_tip": "Use the heel/end slices of a loaf here — they work perfectly",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Western",
    },
    {
        "name": "Pancakes",
        "ingredients": ["flour", "egg", "milk", "butter", "sugar"],
        "steps": [
            "Whisk flour, sugar and a pinch of salt together",
            "Add egg and milk, whisk until smooth",
            "Melt a little butter in a pan over medium heat",
            "Pour batter and cook until bubbles form, then flip",
            "Cook the other side until golden and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 340, "protein": "9g", "carbs": "48g", "fat": "12g"},
        "sustainability_tip": "Batter keeps well overnight in the fridge — make only what you'll eat",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Western",
    },
    {
        "name": "French Toast",
        "ingredients": ["bread", "egg", "milk", "butter", "cinnamon"],
        "steps": [
            "Whisk egg, milk and cinnamon together",
            "Dip bread slices in the mixture, soaking both sides",
            "Melt butter in a pan over medium heat",
            "Fry the soaked bread until golden on both sides",
            "Serve with syrup or fruit",
        ],
        "prep_time": "10 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 360, "protein": "12g", "carbs": "38g", "fat": "17g"},
        "sustainability_tip": "This is the perfect way to use up bread that's gone slightly stale",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Western",
    },
    {
        "name": "Banana Pancakes",
        "ingredients": ["banana", "flour", "egg", "milk"],
        "steps": [
            "Mash the banana in a bowl",
            "Whisk in egg and milk",
            "Fold in flour until just combined",
            "Cook spoonfuls of batter in a lightly greased pan until golden",
            "Flip and cook the other side, then serve",
        ],
        "prep_time": "10 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 320, "protein": "8g", "carbs": "46g", "fat": "10g"},
        "sustainability_tip": "Overripe, spotty bananas make the sweetest pancakes",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Western",
    },
    {
        "name": "Avocado Toast",
        "ingredients": ["bread", "avocado", "lemon", "salt"],
        "steps": [
            "Toast the bread until golden",
            "Mash the avocado with lemon juice and salt",
            "Spread over the toast",
            "Top with chili flakes or an egg if desired",
            "Serve immediately",
        ],
        "prep_time": "5 min",
        "cook_time": "3 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "6g", "carbs": "28g", "fat": "15g"},
        "sustainability_tip": "Keep the avocado pit in the mash to slow browning if not eating right away",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy"],
        "cuisine": "Western",
    },
    {
        "name": "Chicken Curry",
        "ingredients": ["chicken breast", "onion", "garlic", "ginger", "coconut milk", "curry powder"],
        "steps": [
            "Saute onion, garlic and ginger until fragrant",
            "Add curry powder and cook for a minute",
            "Add chicken and brown lightly",
            "Pour in coconut milk and simmer until chicken is cooked through",
            "Serve hot with rice",
        ],
        "prep_time": "15 min",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 460, "protein": "30g", "carbs": "16g", "fat": "30g"},
        "sustainability_tip": "Freeze leftover coconut milk in ice cube trays for future use",
        "diet_tags": ["Halal", "Gluten-Free"],
        "cuisine": "Indian",
    },
    {
        "name": "Beef Stir Fry",
        "ingredients": ["beef", "broccoli", "carrot", "soy sauce", "garlic"],
        "steps": [
            "Slice beef thinly against the grain",
            "Stir-fry beef in a hot wok until browned, set aside",
            "Stir-fry broccoli and carrot until crisp-tender",
            "Return beef to the wok with garlic and soy sauce",
            "Toss everything together and serve hot",
        ],
        "prep_time": "15 min",
        "cook_time": "12 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 400, "protein": "32g", "carbs": "16g", "fat": "22g"},
        "sustainability_tip": "Broccoli stalks are edible — peel and slice them thin instead of discarding",
        "diet_tags": ["High Protein"],
        "cuisine": "Asian",
    },
    {
        "name": "Vegetable Stir Fry",
        "ingredients": ["broccoli", "carrot", "bell pepper", "garlic", "soy sauce"],
        "steps": [
            "Heat oil in a wok over high heat",
            "Add garlic and stir-fry until fragrant",
            "Add broccoli, carrot and bell pepper",
            "Stir-fry until vegetables are crisp-tender",
            "Add soy sauce, toss and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 180, "protein": "5g", "carbs": "22g", "fat": "8g"},
        "sustainability_tip": "Use any vegetables that need using up — this recipe is very flexible",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy"],
        "cuisine": "Asian",
    },
    {
        "name": "Shakshuka",
        "ingredients": ["egg", "tomato", "onion", "bell pepper", "garlic", "cumin"],
        "steps": [
            "Saute onion and bell pepper until soft",
            "Add garlic and cumin, cook until fragrant",
            "Add chopped tomatoes and simmer into a thick sauce",
            "Make wells in the sauce and crack eggs into them",
            "Cover and cook until the eggs are set, then serve with bread",
        ],
        "prep_time": "10 min",
        "cook_time": "20 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 260, "protein": "14g", "carbs": "18g", "fat": "15g"},
        "sustainability_tip": "A great way to use up soft or overripe tomatoes and peppers",
        "diet_tags": ["Vegetarian", "Gluten-Free"],
        "cuisine": "Middle Eastern",
    },
    {
        "name": "Egg Fried Rice",
        "ingredients": ["rice", "egg", "soy sauce", "onion", "garlic"],
        "steps": [
            "Scramble the egg in a hot wok and set aside",
            "Saute garlic and onion until fragrant",
            "Add rice and break up any clumps",
            "Return the egg to the wok and add soy sauce",
            "Toss everything together and serve",
        ],
        "prep_time": "5 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 320, "protein": "10g", "carbs": "52g", "fat": "8g"},
        "sustainability_tip": "The classic way to use up leftover rice before it goes to waste",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Asian",
    },
    {
        "name": "Spaghetti Bolognese",
        "ingredients": ["pasta", "ground beef", "tomato", "onion", "garlic", "carrot"],
        "steps": [
            "Saute onion, garlic and carrot until soft",
            "Add ground beef and brown thoroughly",
            "Stir in chopped tomatoes and simmer for 25 minutes",
            "Boil pasta until al dente",
            "Serve the sauce over the pasta with grated cheese",
        ],
        "prep_time": "15 min",
        "cook_time": "35 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 520, "protein": "28g", "carbs": "58g", "fat": "18g"},
        "sustainability_tip": "Simmer longer with vegetable scraps for extra flavor before straining",
        "diet_tags": ["High Protein"],
        "cuisine": "Italian",
    },
    {
        "name": "Spaghetti Carbonara",
        "ingredients": ["pasta", "egg", "parmesan", "bacon", "black pepper"],
        "steps": [
            "Boil pasta until al dente, reserving some pasta water",
            "Cook bacon until crisp",
            "Whisk egg with grated parmesan and black pepper",
            "Toss hot pasta with bacon off the heat, then quickly stir in the egg mixture",
            "Add a splash of pasta water to loosen the sauce and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 540, "protein": "24g", "carbs": "56g", "fat": "24g"},
        "sustainability_tip": "Save pasta water — its starch is great for thickening sauces",
        "diet_tags": [],
        "cuisine": "Italian",
    },
    {
        "name": "Chicken Parmesan",
        "ingredients": ["chicken breast", "bread crumbs", "egg", "tomato", "mozzarella", "parmesan"],
        "steps": [
            "Flatten chicken breasts to an even thickness",
            "Dip in egg, then coat in bread crumbs mixed with parmesan",
            "Pan-fry until golden on both sides",
            "Top with tomato sauce and mozzarella",
            "Bake until the cheese melts and serve with pasta",
        ],
        "prep_time": "15 min",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 480, "protein": "38g", "carbs": "24g", "fat": "24g"},
        "sustainability_tip": "Stale bread makes excellent homemade bread crumbs",
        "diet_tags": ["High Protein"],
        "cuisine": "Italian",
    },
    {
        "name": "Caprese Salad",
        "ingredients": ["tomato", "mozzarella", "basil", "olive oil"],
        "steps": [
            "Slice tomatoes and mozzarella into rounds",
            "Arrange alternating on a plate",
            "Tuck fresh basil leaves between the slices",
            "Drizzle with olive oil and a pinch of salt",
            "Serve immediately",
        ],
        "prep_time": "10 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 220, "protein": "12g", "carbs": "6g", "fat": "16g"},
        "sustainability_tip": "Ripe, in-season tomatoes taste best and reduce food miles",
        "diet_tags": ["Vegetarian", "Gluten-Free"],
        "cuisine": "Italian",
    },
    {
        "name": "Greek Salad",
        "ingredients": ["tomato", "cucumber", "onion", "feta", "olive oil"],
        "steps": [
            "Chop tomato, cucumber and onion into chunks",
            "Combine in a bowl with crumbled feta",
            "Drizzle with olive oil and a squeeze of lemon",
            "Season with oregano, salt and pepper",
            "Toss gently and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 240, "protein": "8g", "carbs": "12g", "fat": "18g"},
        "sustainability_tip": "Use slightly soft cucumbers and tomatoes here — they still taste great chopped",
        "diet_tags": ["Vegetarian", "Gluten-Free"],
        "cuisine": "Mediterranean",
    },
    {
        "name": "Potato Soup",
        "ingredients": ["potato", "onion", "garlic", "milk", "butter"],
        "steps": [
            "Saute onion and garlic in butter until soft",
            "Add diced potatoes and stock, simmer until tender",
            "Blend partially for a creamy but chunky texture",
            "Stir in milk and heat through",
            "Season and serve with chives",
        ],
        "prep_time": "10 min",
        "cook_time": "25 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 290, "protein": "7g", "carbs": "42g", "fat": "10g"},
        "sustainability_tip": "Potato skins are nutritious — leave them on when possible",
        "diet_tags": ["Vegetarian", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Roasted Vegetables",
        "ingredients": ["potato", "carrot", "broccoli", "olive oil", "garlic"],
        "steps": [
            "Preheat the oven to 200C",
            "Chop vegetables into even chunks",
            "Toss with olive oil, garlic, salt and pepper",
            "Roast for 25-30 minutes, turning halfway",
            "Serve as a side or over rice",
        ],
        "prep_time": "10 min",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 210, "protein": "4g", "carbs": "30g", "fat": "9g"},
        "sustainability_tip": "This is the perfect recipe for odds and ends of vegetables nearing their expiry",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Beef Stew",
        "ingredients": ["beef", "potato", "carrot", "onion", "garlic"],
        "steps": [
            "Brown beef chunks in a large pot",
            "Add onion and garlic, cook until soft",
            "Add potato, carrot and stock",
            "Simmer covered for 1.5-2 hours until beef is tender",
            "Season to taste and serve hot",
        ],
        "prep_time": "15 min",
        "cook_time": "120 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 420, "protein": "30g", "carbs": "28g", "fat": "18g"},
        "sustainability_tip": "Tougher, cheaper cuts of beef work beautifully in a long-simmered stew",
        "diet_tags": ["High Protein", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Chicken Soup with Rice",
        "ingredients": ["chicken breast", "rice", "carrot", "onion", "garlic"],
        "steps": [
            "Saute onion, garlic and carrot until fragrant",
            "Add chicken and stock, bring to a simmer",
            "Cook until chicken is tender, then shred",
            "Add rice and cook until tender",
            "Season and serve hot",
        ],
        "prep_time": "10 min",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 340, "protein": "26g", "carbs": "36g", "fat": "8g"},
        "sustainability_tip": "Use the chicken carcass for stock instead of store-bought",
        "diet_tags": ["Halal", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Egg Salad Sandwich",
        "ingredients": ["egg", "bread", "mayonnaise", "mustard"],
        "steps": [
            "Hard boil the eggs, then cool and peel",
            "Chop the eggs and mix with mayonnaise and mustard",
            "Season with salt and pepper",
            "Spread onto bread slices",
            "Slice and serve",
        ],
        "prep_time": "15 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 340, "protein": "14g", "carbs": "28g", "fat": "19g"},
        "sustainability_tip": "Eggshells can be crushed and added to compost or garden soil",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Western",
    },
    {
        "name": "Tuna Salad",
        "ingredients": ["tuna", "mayonnaise", "onion", "lemon"],
        "steps": [
            "Drain the tuna well",
            "Mix with mayonnaise, finely diced onion and a squeeze of lemon",
            "Season with salt and pepper",
            "Serve on bread, crackers or over greens",
        ],
        "prep_time": "10 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 280, "protein": "24g", "carbs": "4g", "fat": "18g"},
        "sustainability_tip": "Choose pole-and-line caught tuna where possible for sustainable fishing",
        "diet_tags": ["Pescatarian", "High Protein"],
        "cuisine": "Western",
    },
    {
        "name": "Grilled Chicken Breast",
        "ingredients": ["chicken breast", "olive oil", "garlic", "lemon"],
        "steps": [
            "Marinate chicken in olive oil, garlic and lemon juice for 20 minutes",
            "Preheat a grill or grill pan to medium-high",
            "Grill chicken 6-7 minutes per side until cooked through",
            "Rest for 5 minutes before slicing",
            "Serve with a side salad or vegetables",
        ],
        "prep_time": "20 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 280, "protein": "36g", "carbs": "2g", "fat": "14g"},
        "sustainability_tip": "Marinate in a reusable container instead of a disposable bag",
        "diet_tags": ["High Protein", "Halal", "Gluten-Free", "Keto"],
        "cuisine": "Western",
    },
    {
        "name": "Baked Chicken Thighs",
        "ingredients": ["chicken thigh", "garlic", "olive oil", "paprika"],
        "steps": [
            "Preheat the oven to 200C",
            "Rub chicken thighs with olive oil, garlic and paprika",
            "Place skin-side up on a baking tray",
            "Bake for 35-40 minutes until golden and cooked through",
            "Rest for a few minutes before serving",
        ],
        "prep_time": "10 min",
        "cook_time": "40 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 360, "protein": "28g", "carbs": "2g", "fat": "26g"},
        "sustainability_tip": "Save the rendered fat and pan juices to flavor rice or vegetables",
        "diet_tags": ["High Protein", "Halal", "Gluten-Free", "Keto"],
        "cuisine": "Western",
    },
    {
        "name": "Vegetable Curry",
        "ingredients": ["potato", "carrot", "onion", "garlic", "ginger", "coconut milk", "curry powder"],
        "steps": [
            "Saute onion, garlic and ginger until fragrant",
            "Add curry powder and cook for a minute",
            "Add potato and carrot, stir to coat",
            "Pour in coconut milk and simmer until vegetables are tender",
            "Serve hot with rice",
        ],
        "prep_time": "15 min",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 340, "protein": "6g", "carbs": "38g", "fat": "18g"},
        "sustainability_tip": "Root vegetables nearing the end of their shelf life are perfect here",
        "diet_tags": ["Vegan", "Vegetarian", "Gluten-Free"],
        "cuisine": "Indian",
    },
    {
        "name": "Lentil Soup",
        "ingredients": ["lentils", "onion", "carrot", "garlic", "tomato"],
        "steps": [
            "Saute onion, carrot and garlic until soft",
            "Add lentils, chopped tomato and stock",
            "Simmer for 25-30 minutes until lentils are tender",
            "Blend partially if a creamier texture is desired",
            "Season and serve with bread",
        ],
        "prep_time": "10 min",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "16g", "carbs": "40g", "fat": "4g"},
        "sustainability_tip": "Lentils are a low-water-footprint protein — a great sustainable staple",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Middle Eastern",
    },
    {
        "name": "Chickpea Salad",
        "ingredients": ["chickpeas", "tomato", "cucumber", "onion", "olive oil", "lemon"],
        "steps": [
            "Drain and rinse the chickpeas",
            "Chop tomato, cucumber and onion",
            "Combine everything in a bowl",
            "Dress with olive oil, lemon juice, salt and pepper",
            "Toss and serve chilled or at room temperature",
        ],
        "prep_time": "15 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 300, "protein": "12g", "carbs": "38g", "fat": "12g"},
        "sustainability_tip": "Canned chickpeas keep well and reduce fresh produce waste",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Mediterranean",
    },
    {
        "name": "Fried Egg Rice Bowl",
        "ingredients": ["rice", "egg", "soy sauce", "green onion"],
        "steps": [
            "Cook rice and place in a bowl",
            "Fry an egg sunny-side up",
            "Place the fried egg on top of the rice",
            "Drizzle with soy sauce and top with sliced green onion",
            "Mix everything together and serve",
        ],
        "prep_time": "5 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 340, "protein": "12g", "carbs": "48g", "fat": "10g"},
        "sustainability_tip": "A simple, quick meal that uses just one egg and pantry basics",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Asian",
    },
    {
        "name": "Mashed Potatoes",
        "ingredients": ["potato", "butter", "milk", "salt"],
        "steps": [
            "Peel and chop the potatoes into even chunks",
            "Boil until fork-tender",
            "Drain and return to the pot",
            "Mash with butter and warm milk until smooth",
            "Season with salt and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "5g", "carbs": "38g", "fat": "10g"},
        "sustainability_tip": "Potato peels can be roasted into crispy chips instead of thrown away",
        "diet_tags": ["Vegetarian", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Garlic Bread",
        "ingredients": ["bread", "butter", "garlic", "parsley"],
        "steps": [
            "Mix softened butter with minced garlic and chopped parsley",
            "Slice the bread and spread the garlic butter generously",
            "Wrap in foil or place on a tray",
            "Bake at 180C for 10 minutes until warm and toasted",
            "Serve alongside pasta or soup",
        ],
        "prep_time": "10 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 220, "protein": "5g", "carbs": "26g", "fat": "12g"},
        "sustainability_tip": "A great use for a baguette that's starting to go stale",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Western",
    },
    {
        "name": "Cheese Quesadilla",
        "ingredients": ["tortilla", "cheese", "butter"],
        "steps": [
            "Sprinkle cheese over half of a tortilla",
            "Fold the tortilla in half",
            "Cook in a buttered pan until golden and cheese melts",
            "Flip carefully and cook the other side",
            "Slice into wedges and serve",
        ],
        "prep_time": "5 min",
        "cook_time": "8 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 340, "protein": "14g", "carbs": "26g", "fat": "20g"},
        "sustainability_tip": "Use up small amounts of leftover cheese ends here",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Mexican",
    },
    {
        "name": "Chicken Quesadilla",
        "ingredients": ["tortilla", "chicken breast", "cheese", "onion", "bell pepper"],
        "steps": [
            "Cook diced chicken with onion and bell pepper until done",
            "Sprinkle cheese and the chicken mixture over half a tortilla",
            "Fold and cook in a pan until golden on both sides",
            "Cheese should be fully melted",
            "Slice into wedges and serve with salsa",
        ],
        "prep_time": "15 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 420, "protein": "28g", "carbs": "30g", "fat": "22g"},
        "sustainability_tip": "Great way to use up small amounts of leftover cooked chicken",
        "diet_tags": ["High Protein", "Halal"],
        "cuisine": "Mexican",
    },
    {
        "name": "Vegetable Omelette",
        "ingredients": ["egg", "bell pepper", "onion", "tomato", "cheese"],
        "steps": [
            "Whisk the eggs with a pinch of salt",
            "Saute diced bell pepper, onion and tomato until soft",
            "Pour the eggs over the vegetables in the pan",
            "Sprinkle cheese on top and cook until set",
            "Fold and serve warm",
        ],
        "prep_time": "10 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 310, "protein": "20g", "carbs": "8g", "fat": "21g"},
        "sustainability_tip": "A perfect way to use small amounts of leftover vegetables",
        "diet_tags": ["Vegetarian", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Baked Sweet Potato",
        "ingredients": ["sweet potato", "butter", "salt"],
        "steps": [
            "Preheat the oven to 200C",
            "Pierce the sweet potato a few times with a fork",
            "Bake for 40-45 minutes until soft",
            "Slice open and add a knob of butter",
            "Season with salt and serve",
        ],
        "prep_time": "5 min",
        "cook_time": "45 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 210, "protein": "3g", "carbs": "42g", "fat": "5g"},
        "sustainability_tip": "Sweet potato skins are edible and packed with fiber — no need to peel",
        "diet_tags": ["Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Stir Fried Broccoli with Garlic",
        "ingredients": ["broccoli", "garlic", "soy sauce", "olive oil"],
        "steps": [
            "Cut broccoli into florets",
            "Heat oil in a pan and add garlic",
            "Add broccoli and stir-fry for 3-4 minutes",
            "Add a splash of water and cover briefly to steam",
            "Finish with soy sauce and serve",
        ],
        "prep_time": "5 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 120, "protein": "5g", "carbs": "12g", "fat": "6g"},
        "sustainability_tip": "Peel and slice the broccoli stalk thin to cook alongside the florets",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy"],
        "cuisine": "Asian",
    },
    {
        "name": "Tomato Egg Stir Fry",
        "ingredients": ["tomato", "egg", "green onion", "salt"],
        "steps": [
            "Whisk the eggs with a pinch of salt",
            "Scramble the eggs in a hot pan and set aside",
            "Stir-fry chopped tomatoes until they release their juices",
            "Return the eggs to the pan and toss together",
            "Garnish with green onion and serve with rice",
        ],
        "prep_time": "5 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 240, "protein": "14g", "carbs": "10g", "fat": "16g"},
        "sustainability_tip": "A classic quick dish for tomatoes that are a little too soft to eat raw",
        "diet_tags": ["Vegetarian", "Gluten-Free"],
        "cuisine": "Asian",
    },
    {
        "name": "Banana Oat Smoothie",
        "ingredients": ["banana", "oats", "milk", "honey"],
        "steps": [
            "Add banana, oats, milk and honey to a blender",
            "Blend until smooth",
            "Add ice if a colder, thicker texture is desired",
            "Pour into a glass and serve",
        ],
        "prep_time": "5 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 280, "protein": "9g", "carbs": "50g", "fat": "5g"},
        "sustainability_tip": "Overripe bananas blend even sweeter — don't toss them",
        "diet_tags": ["Vegetarian", "Healthy"],
        "cuisine": "Western",
    },
    {
        "name": "Peanut Butter Banana Toast",
        "ingredients": ["bread", "peanut butter", "banana"],
        "steps": [
            "Toast the bread",
            "Spread a generous layer of peanut butter",
            "Top with sliced banana",
            "Drizzle with honey if desired and serve",
        ],
        "prep_time": "5 min",
        "cook_time": "2 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 320, "protein": "10g", "carbs": "40g", "fat": "14g"},
        "sustainability_tip": "Use up bananas that are just starting to brown",
        "diet_tags": ["Vegetarian", "Healthy"],
        "cuisine": "Western",
    },
    {
        "name": "Chicken Sandwich",
        "ingredients": ["chicken breast", "bread", "lettuce", "tomato", "mayonnaise"],
        "steps": [
            "Season and grill or pan-sear the chicken breast until cooked through",
            "Toast the bread lightly",
            "Spread mayonnaise on the bread",
            "Layer chicken, lettuce and tomato",
            "Close the sandwich, slice and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "12 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 420, "protein": "32g", "carbs": "30g", "fat": "18g"},
        "sustainability_tip": "Leftover roast chicken works perfectly here instead of cooking fresh",
        "diet_tags": ["High Protein", "Halal"],
        "cuisine": "Western",
    },
    {
        "name": "Fruit Salad",
        "ingredients": ["banana", "apple", "orange", "honey", "lemon"],
        "steps": [
            "Chop all the fruit into bite-sized pieces",
            "Combine in a large bowl",
            "Drizzle with honey and a squeeze of lemon juice to prevent browning",
            "Toss gently and chill before serving",
        ],
        "prep_time": "10 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 160, "protein": "2g", "carbs": "40g", "fat": "0g"},
        "sustainability_tip": "A great way to use up fruit that's a little too soft for eating on its own",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Cucumber Yogurt Salad",
        "ingredients": ["cucumber", "yogurt", "garlic", "mint"],
        "steps": [
            "Grate or thinly slice the cucumber",
            "Mix with yogurt and minced garlic",
            "Add chopped mint and a pinch of salt",
            "Chill for 10 minutes before serving",
        ],
        "prep_time": "10 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 110, "protein": "6g", "carbs": "10g", "fat": "4g"},
        "sustainability_tip": "A refreshing side that uses up cucumbers before they turn soft",
        "diet_tags": ["Vegetarian", "Gluten-Free", "Healthy"],
        "cuisine": "Middle Eastern",
    },
    {
        "name": "Baked Ziti",
        "ingredients": ["pasta", "tomato", "mozzarella", "ricotta", "garlic"],
        "steps": [
            "Boil the pasta until just shy of al dente",
            "Mix with tomato sauce, ricotta and garlic",
            "Transfer to a baking dish and top with mozzarella",
            "Bake at 190C until bubbling and golden",
            "Rest for 5 minutes before serving",
        ],
        "prep_time": "15 min",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 480, "protein": "22g", "carbs": "56g", "fat": "18g"},
        "sustainability_tip": "Freezes well — make a double batch to reduce future cooking energy use",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Italian",
    },
    {
        "name": "Chicken and Vegetable Soup",
        "ingredients": ["chicken breast", "potato", "carrot", "onion", "celery"],
        "steps": [
            "Saute onion, carrot and celery until soft",
            "Add chicken and stock, bring to a simmer",
            "Add diced potato and cook until tender",
            "Shred the cooked chicken and return to the pot",
            "Season and serve hot",
        ],
        "prep_time": "15 min",
        "cook_time": "35 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 300, "protein": "26g", "carbs": "26g", "fat": "8g"},
        "sustainability_tip": "Vegetable ends (celery leaves, carrot tops) can flavor the broth too",
        "diet_tags": ["Halal", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Honey Garlic Chicken",
        "ingredients": ["chicken thigh", "honey", "garlic", "soy sauce"],
        "steps": [
            "Season and sear chicken thighs until golden",
            "Mix honey, minced garlic and soy sauce",
            "Pour the sauce over the chicken in the pan",
            "Simmer until the sauce thickens and coats the chicken",
            "Serve with rice and steamed vegetables",
        ],
        "prep_time": "10 min",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 380, "protein": "28g", "carbs": "20g", "fat": "20g"},
        "sustainability_tip": "Local honey supports local beekeepers and pollinators",
        "diet_tags": ["Halal"],
        "cuisine": "Asian",
    },
    # --- Thai ---
    {
        "name": "Pad Thai",
        "ingredients": ["rice noodles", "egg", "shrimp", "bean sprouts", "peanut", "lime", "tofu"],
        "steps": [
            "Soak rice noodles in warm water until pliable",
            "Stir-fry tofu and shrimp until cooked, push to one side",
            "Crack in the egg and scramble it into the pan",
            "Add noodles, bean sprouts and pad thai sauce, toss to combine",
            "Top with crushed peanuts and a squeeze of lime",
        ],
        "prep_time": "15 min",
        "cook_time": "15 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 420, "protein": "22g", "carbs": "54g", "fat": "14g"},
        "sustainability_tip": "Shrimp shells can be frozen and saved for stock instead of discarded",
        "diet_tags": ["Pescatarian"],
        "cuisine": "Thai",
    },
    {
        "name": "Green Curry Chicken",
        "ingredients": ["chicken breast", "green curry paste", "coconut milk", "eggplant", "basil", "fish sauce"],
        "steps": [
            "Fry green curry paste in a splash of coconut milk until fragrant",
            "Add chicken and cook until browned",
            "Pour in the remaining coconut milk and bring to a simmer",
            "Add eggplant and cook until tender",
            "Stir in fish sauce and basil leaves, serve with rice",
        ],
        "prep_time": "15 min",
        "cook_time": "20 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 420, "protein": "28g", "carbs": "14g", "fat": "28g"},
        "sustainability_tip": "Freeze leftover curry paste in small portions to use only what you need",
        "diet_tags": ["Gluten-Free"],
        "cuisine": "Thai",
    },
    {
        "name": "Tom Yum Soup",
        "ingredients": ["shrimp", "lemongrass", "lime", "chili", "mushroom", "fish sauce", "cilantro"],
        "steps": [
            "Bring stock to a boil with lemongrass and chili",
            "Add mushrooms and simmer for 5 minutes",
            "Add shrimp and cook until just pink",
            "Season with fish sauce and lime juice",
            "Garnish with cilantro and serve hot",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 180, "protein": "18g", "carbs": "10g", "fat": "6g"},
        "sustainability_tip": "Use the whole mushroom, including stems, to reduce food waste",
        "diet_tags": ["Pescatarian", "Gluten-Free", "Healthy"],
        "cuisine": "Thai",
    },
    {
        "name": "Thai Basil Chicken",
        "ingredients": ["chicken breast", "thai basil", "garlic", "chili", "soy sauce", "egg"],
        "steps": [
            "Mince the chicken breast or use ground chicken",
            "Stir-fry garlic and chili in hot oil until fragrant",
            "Add chicken and cook until browned",
            "Add soy sauce and toss in thai basil off the heat",
            "Serve over rice with a fried egg on top",
        ],
        "prep_time": "10 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 360, "protein": "32g", "carbs": "8g", "fat": "20g"},
        "sustainability_tip": "A fast weeknight dish that helps use up basil before it wilts",
        "diet_tags": ["High Protein"],
        "cuisine": "Thai",
    },
    {
        "name": "Mango Sticky Rice",
        "ingredients": ["rice", "mango", "coconut milk", "sugar"],
        "steps": [
            "Soak glutinous rice and steam until tender",
            "Warm coconut milk with sugar and a pinch of salt",
            "Pour most of the coconut milk over the hot rice and let it absorb",
            "Slice the mango",
            "Serve rice topped with mango and the remaining coconut sauce",
        ],
        "prep_time": "10 min",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 380, "protein": "5g", "carbs": "68g", "fat": "10g"},
        "sustainability_tip": "Overripe mango works perfectly and tastes even sweeter here",
        "diet_tags": ["Vegan", "Vegetarian", "Gluten-Free"],
        "cuisine": "Thai",
    },
    # --- Chinese ---
    {
        "name": "Kung Pao Chicken",
        "ingredients": ["chicken breast", "peanut", "bell pepper", "soy sauce", "garlic", "chili"],
        "steps": [
            "Cut chicken into bite-sized cubes",
            "Stir-fry chicken in hot oil until browned",
            "Add garlic, chili and bell pepper, stir-fry briefly",
            "Add soy sauce and toss to coat",
            "Stir in roasted peanuts and serve with rice",
        ],
        "prep_time": "15 min",
        "cook_time": "15 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 400, "protein": "30g", "carbs": "16g", "fat": "24g"},
        "sustainability_tip": "Buy peanuts in bulk to cut down on packaging waste",
        "diet_tags": ["High Protein"],
        "cuisine": "Chinese",
    },
    {
        "name": "Sweet and Sour Pork",
        "ingredients": ["pork", "bell pepper", "pineapple", "vinegar", "sugar", "soy sauce"],
        "steps": [
            "Cut pork into chunks and fry until golden and cooked through",
            "Stir-fry bell pepper until just tender",
            "Mix vinegar, sugar and soy sauce to make the sauce",
            "Add pineapple and the sauce to the pan, simmer until thickened",
            "Return pork to the pan, toss to coat and serve with rice",
        ],
        "prep_time": "15 min",
        "cook_time": "20 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 440, "protein": "26g", "carbs": "34g", "fat": "20g"},
        "sustainability_tip": "Use canned pineapple in juice rather than syrup to reduce added sugar waste",
        "diet_tags": [],
        "cuisine": "Chinese",
    },
    {
        "name": "Mapo Tofu",
        "ingredients": ["tofu", "ground pork", "chili bean paste", "garlic", "green onion"],
        "steps": [
            "Cut tofu into cubes and set aside",
            "Brown the ground pork in a hot pan",
            "Add garlic and chili bean paste, cook until fragrant",
            "Add tofu and a splash of stock, simmer gently for 5 minutes",
            "Garnish with green onion and serve over rice",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 340, "protein": "22g", "carbs": "10g", "fat": "22g"},
        "sustainability_tip": "Tofu is a low-water, low-carbon protein — a sustainable swap for meat",
        "diet_tags": ["High Protein"],
        "cuisine": "Chinese",
    },
    {
        "name": "Chinese Fried Noodles",
        "ingredients": ["noodles", "cabbage", "carrot", "soy sauce", "garlic", "egg"],
        "steps": [
            "Boil noodles until just tender, then drain",
            "Scramble the egg in a hot wok and set aside",
            "Stir-fry garlic, cabbage and carrot until crisp-tender",
            "Add noodles and soy sauce, toss to combine",
            "Return the egg to the wok and mix through before serving",
        ],
        "prep_time": "10 min",
        "cook_time": "12 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 360, "protein": "12g", "carbs": "58g", "fat": "8g"},
        "sustainability_tip": "Odds and ends of cabbage and carrot work perfectly in this flexible dish",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Chinese",
    },
    {
        "name": "Hot and Sour Soup",
        "ingredients": ["tofu", "mushroom", "egg", "vinegar", "soy sauce", "white pepper"],
        "steps": [
            "Bring stock to a simmer with sliced mushrooms",
            "Add diced tofu and cook for a few minutes",
            "Season with vinegar, soy sauce and white pepper",
            "Drizzle in beaten egg while stirring to form ribbons",
            "Serve hot, adjusting sourness and spice to taste",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 190, "protein": "14g", "carbs": "10g", "fat": "10g"},
        "sustainability_tip": "A great way to use up odd bits of mushroom and tofu before they spoil",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Chinese",
    },
    {
        "name": "Char Siu Chicken",
        "ingredients": ["chicken thigh", "honey", "soy sauce", "garlic", "five spice"],
        "steps": [
            "Mix honey, soy sauce, garlic and five spice into a marinade",
            "Marinate chicken thighs for at least 20 minutes",
            "Roast or grill at high heat, basting with marinade",
            "Cook until caramelized and cooked through, about 20 minutes",
            "Rest briefly, slice and serve with rice",
        ],
        "prep_time": "20 min",
        "cook_time": "20 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 380, "protein": "28g", "carbs": "18g", "fat": "22g"},
        "sustainability_tip": "Marinate in a reusable bowl covered with a plate instead of cling film",
        "diet_tags": ["Halal"],
        "cuisine": "Chinese",
    },
    # --- Japanese ---
    {
        "name": "Chicken Teriyaki",
        "ingredients": ["chicken thigh", "soy sauce", "honey", "garlic", "ginger"],
        "steps": [
            "Mix soy sauce, honey, garlic and ginger into a sauce",
            "Sear chicken thighs skin-side down until golden",
            "Flip and cook through",
            "Pour in the sauce and simmer until glossy and thickened",
            "Slice and serve over rice with the sauce spooned on top",
        ],
        "prep_time": "10 min",
        "cook_time": "18 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 380, "protein": "28g", "carbs": "20g", "fat": "20g"},
        "sustainability_tip": "Use bone-in thighs and save the bones for a quick stock",
        "diet_tags": ["Halal"],
        "cuisine": "Japanese",
    },
    {
        "name": "Miso Soup",
        "ingredients": ["tofu", "miso paste", "seaweed", "green onion"],
        "steps": [
            "Bring water or dashi to a gentle simmer",
            "Whisk in miso paste until dissolved (do not boil)",
            "Add cubed tofu and seaweed, warm through",
            "Garnish with sliced green onion",
            "Serve immediately as a starter or side",
        ],
        "prep_time": "5 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 90, "protein": "7g", "carbs": "6g", "fat": "4g"},
        "sustainability_tip": "Miso paste keeps for months in the fridge — buy once, use often",
        "diet_tags": ["Vegetarian", "Healthy"],
        "cuisine": "Japanese",
    },
    {
        "name": "Salmon Onigiri",
        "ingredients": ["rice", "salmon", "seaweed", "salt"],
        "steps": [
            "Cook rice and season lightly with salt",
            "Flake cooked or canned salmon",
            "Wet hands and shape rice around a spoonful of salmon into a triangle",
            "Wrap a strip of seaweed around the base",
            "Serve at room temperature or pack for later",
        ],
        "prep_time": "15 min",
        "cook_time": "5 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 300, "protein": "18g", "carbs": "44g", "fat": "6g"},
        "sustainability_tip": "A great way to repurpose small amounts of leftover cooked salmon",
        "diet_tags": ["Pescatarian"],
        "cuisine": "Japanese",
    },
    {
        "name": "Yaki Udon",
        "ingredients": ["udon noodles", "cabbage", "carrot", "soy sauce", "pork"],
        "steps": [
            "Cook udon noodles according to packet instructions and drain",
            "Stir-fry sliced pork until browned",
            "Add cabbage and carrot, stir-fry until tender",
            "Add noodles and soy sauce, toss everything together",
            "Serve hot straight from the wok",
        ],
        "prep_time": "10 min",
        "cook_time": "12 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 420, "protein": "20g", "carbs": "56g", "fat": "12g"},
        "sustainability_tip": "Fresh udon freezes well — buy in bulk to reduce packaging trips",
        "diet_tags": [],
        "cuisine": "Japanese",
    },
    {
        "name": "Japanese Curry",
        "ingredients": ["potato", "carrot", "onion", "chicken breast", "curry roux"],
        "steps": [
            "Brown chicken pieces in a large pot",
            "Add onion, carrot and potato, cook briefly",
            "Cover with water and simmer until vegetables are tender",
            "Break in curry roux blocks and stir until dissolved and thickened",
            "Simmer a few more minutes and serve over rice",
        ],
        "prep_time": "15 min",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 440, "protein": "24g", "carbs": "48g", "fat": "16g"},
        "sustainability_tip": "A one-pot meal that's perfect for using up root vegetables before they soften",
        "diet_tags": ["Halal"],
        "cuisine": "Japanese",
    },
    # --- Korean ---
    {
        "name": "Korean Bibimbap",
        "ingredients": ["rice", "egg", "carrot", "spinach", "bean sprouts", "gochujang"],
        "steps": [
            "Cook rice and place in a bowl",
            "Blanch spinach and bean sprouts separately, season lightly",
            "Saute julienned carrot until just tender",
            "Fry an egg sunny-side up",
            "Arrange vegetables and egg over rice, top with gochujang and mix before eating",
        ],
        "prep_time": "15 min",
        "cook_time": "15 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 380, "protein": "14g", "carbs": "58g", "fat": "10g"},
        "sustainability_tip": "A flexible dish — swap in whatever vegetables need using up",
        "diet_tags": ["Vegetarian", "Healthy"],
        "cuisine": "Korean",
    },
    {
        "name": "Korean Beef Bulgogi",
        "ingredients": ["beef", "soy sauce", "garlic", "sugar", "sesame oil", "green onion"],
        "steps": [
            "Slice beef thinly against the grain",
            "Mix soy sauce, garlic, sugar and sesame oil into a marinade",
            "Marinate beef for at least 20 minutes",
            "Sear beef in a hot pan until caramelized",
            "Garnish with green onion and serve with rice",
        ],
        "prep_time": "20 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 400, "protein": "30g", "carbs": "14g", "fat": "24g"},
        "sustainability_tip": "Thin-sliced cheaper beef cuts work just as well as premium cuts here",
        "diet_tags": ["High Protein"],
        "cuisine": "Korean",
    },
    {
        "name": "Kimchi Fried Rice",
        "ingredients": ["rice", "kimchi", "egg", "soy sauce", "green onion"],
        "steps": [
            "Chop kimchi and stir-fry until slightly caramelized",
            "Add rice and break up any clumps",
            "Season with soy sauce and a splash of kimchi juice",
            "Fry an egg sunny-side up separately",
            "Top the rice with the fried egg and sliced green onion",
        ],
        "prep_time": "5 min",
        "cook_time": "12 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 360, "protein": "10g", "carbs": "56g", "fat": "10g"},
        "sustainability_tip": "The classic way to use up rice and kimchi before they go past their best",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Korean",
    },
    {
        "name": "Korean Spicy Chicken",
        "ingredients": ["chicken thigh", "gochujang", "cabbage", "sweet potato", "garlic"],
        "steps": [
            "Mix gochujang with garlic and a little sugar for the sauce",
            "Toss chicken pieces in the sauce",
            "Stir-fry chicken until browned",
            "Add cabbage and sweet potato, cook until tender",
            "Serve hot with steamed rice",
        ],
        "prep_time": "15 min",
        "cook_time": "20 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 420, "protein": "28g", "carbs": "30g", "fat": "20g"},
        "sustainability_tip": "Sweet potato skins are edible — leave them on to reduce peel waste",
        "diet_tags": ["Halal"],
        "cuisine": "Korean",
    },
    # --- Indian ---
    {
        "name": "Butter Chicken",
        "ingredients": ["chicken breast", "tomato", "butter", "cream", "garam masala", "garlic"],
        "steps": [
            "Marinate chicken in yogurt and spices if time allows",
            "Sear chicken pieces until browned, then set aside",
            "Saute garlic in butter, add tomato and garam masala, simmer into a sauce",
            "Blend the sauce until smooth, then stir in cream",
            "Return chicken to the sauce and simmer until cooked through",
        ],
        "prep_time": "15 min",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 460, "protein": "30g", "carbs": "12g", "fat": "32g"},
        "sustainability_tip": "Overripe tomatoes blend down beautifully into the sauce base",
        "diet_tags": ["Gluten-Free"],
        "cuisine": "Indian",
    },
    {
        "name": "Palak Paneer",
        "ingredients": ["paneer", "spinach", "garlic", "onion", "cream"],
        "steps": [
            "Blanch spinach briefly, then blend into a puree",
            "Saute onion and garlic until soft",
            "Add the spinach puree and simmer for a few minutes",
            "Add cubed paneer and stir gently to coat",
            "Finish with a swirl of cream and serve with rice or bread",
        ],
        "prep_time": "15 min",
        "cook_time": "20 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 340, "protein": "16g", "carbs": "12g", "fat": "26g"},
        "sustainability_tip": "Wilting spinach still purees beautifully — no need to discard it",
        "diet_tags": ["Vegetarian", "Gluten-Free"],
        "cuisine": "Indian",
    },
    {
        "name": "Chana Masala",
        "ingredients": ["chickpeas", "tomato", "onion", "garlic", "garam masala"],
        "steps": [
            "Saute onion and garlic until golden",
            "Add tomato and garam masala, cook into a thick sauce",
            "Add chickpeas and a splash of water",
            "Simmer for 15 minutes until the flavors meld",
            "Serve hot with rice or flatbread",
        ],
        "prep_time": "10 min",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 300, "protein": "14g", "carbs": "42g", "fat": "8g"},
        "sustainability_tip": "Canned chickpeas are shelf-stable and reduce fresh produce waste",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy"],
        "cuisine": "Indian",
    },
    {
        "name": "Dal Tadka",
        "ingredients": ["lentils", "onion", "garlic", "tomato", "cumin"],
        "steps": [
            "Boil lentils with turmeric until soft",
            "In a separate pan, fry cumin seeds, garlic and onion until golden",
            "Add tomato and cook until softened",
            "Pour the tempering over the cooked lentils and stir",
            "Simmer briefly and serve with rice",
        ],
        "prep_time": "10 min",
        "cook_time": "25 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "15g", "carbs": "38g", "fat": "6g"},
        "sustainability_tip": "Lentils are one of the most water-efficient proteins to cook with",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Indian",
    },
    {
        "name": "Aloo Gobi",
        "ingredients": ["potato", "cauliflower", "onion", "garlic", "turmeric"],
        "steps": [
            "Saute onion and garlic with turmeric and cumin",
            "Add potato and cauliflower florets",
            "Stir to coat in the spices",
            "Cover and cook until vegetables are tender, stirring occasionally",
            "Season and serve with flatbread or rice",
        ],
        "prep_time": "10 min",
        "cook_time": "25 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 220, "protein": "5g", "carbs": "36g", "fat": "7g"},
        "sustainability_tip": "Cauliflower leaves are edible too — chop and cook them in",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Indian",
    },
    # --- American ---
    {
        "name": "Classic Cheeseburger",
        "ingredients": ["ground beef", "cheese", "bun", "lettuce", "tomato", "onion"],
        "steps": [
            "Shape ground beef into patties and season with salt and pepper",
            "Grill or pan-fry patties to the desired doneness",
            "Top with cheese in the last minute so it melts",
            "Toast the buns lightly",
            "Assemble with lettuce, tomato and onion",
        ],
        "prep_time": "10 min",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 520, "protein": "28g", "carbs": "32g", "fat": "30g"},
        "sustainability_tip": "Use vegetable trimmings from the lettuce and tomato for a stock bag",
        "diet_tags": ["High Protein"],
        "cuisine": "American",
    },
    {
        "name": "BBQ Pulled Pork Sandwich",
        "ingredients": ["pork", "bbq sauce", "bun", "cabbage"],
        "steps": [
            "Slow-cook pork shoulder until it shreds easily with a fork",
            "Shred the pork and mix with bbq sauce",
            "Shred cabbage for a quick slaw",
            "Toast the buns",
            "Pile pork and slaw onto the buns and serve",
        ],
        "prep_time": "15 min",
        "cook_time": "180 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 540, "protein": "32g", "carbs": "40g", "fat": "26g"},
        "sustainability_tip": "Cheaper, tougher cuts of pork shoulder are ideal for slow cooking",
        "diet_tags": ["High Protein"],
        "cuisine": "American",
    },
    {
        "name": "Mac and Cheese",
        "ingredients": ["macaroni", "cheese", "milk", "butter", "flour"],
        "steps": [
            "Boil macaroni until al dente and drain",
            "Melt butter and whisk in flour to make a roux",
            "Gradually whisk in milk until smooth and thickened",
            "Stir in cheese until melted",
            "Combine with the macaroni and serve hot",
        ],
        "prep_time": "5 min",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 480, "protein": "18g", "carbs": "52g", "fat": "22g"},
        "sustainability_tip": "Use up small odds and ends of different cheeses in the sauce",
        "diet_tags": ["Vegetarian"],
        "cuisine": "American",
    },
    {
        "name": "Buffalo Chicken Wings",
        "ingredients": ["chicken wing", "hot sauce", "butter", "garlic"],
        "steps": [
            "Bake or fry chicken wings until crispy and cooked through",
            "Melt butter and mix with hot sauce and minced garlic",
            "Toss the cooked wings in the sauce until fully coated",
            "Serve hot with celery sticks and a dipping sauce",
        ],
        "prep_time": "10 min",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 420, "protein": "26g", "carbs": "2g", "fat": "34g"},
        "sustainability_tip": "Baking instead of deep-frying saves oil and energy",
        "diet_tags": ["Halal", "Gluten-Free"],
        "cuisine": "American",
    },
    {
        "name": "Clam Chowder",
        "ingredients": ["clam", "potato", "onion", "celery", "milk"],
        "steps": [
            "Saute onion and celery until soft",
            "Add diced potato and clam juice, simmer until potato is tender",
            "Stir in milk and clams",
            "Heat through gently without boiling",
            "Season and serve with crusty bread",
        ],
        "prep_time": "15 min",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 340, "protein": "18g", "carbs": "32g", "fat": "14g"},
        "sustainability_tip": "Choose sustainably harvested clams where available",
        "diet_tags": ["Pescatarian"],
        "cuisine": "American",
    },
    {
        "name": "Cornbread",
        "ingredients": ["cornmeal", "flour", "milk", "egg", "butter"],
        "steps": [
            "Mix cornmeal, flour, sugar and baking powder",
            "Whisk in milk, egg and melted butter",
            "Pour batter into a greased baking pan",
            "Bake at 200C for 20-25 minutes until golden",
            "Cool slightly, slice and serve warm",
        ],
        "prep_time": "10 min",
        "cook_time": "25 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "6g", "carbs": "38g", "fat": "9g"},
        "sustainability_tip": "Freeze leftover slices instead of letting them go stale and get thrown out",
        "diet_tags": ["Vegetarian"],
        "cuisine": "American",
    },
    {
        "name": "American Pancake Stack",
        "ingredients": ["flour", "egg", "milk", "butter", "maple syrup"],
        "steps": [
            "Whisk flour, sugar and baking powder together",
            "Add egg and milk, whisk until just combined",
            "Cook spoonfuls of batter in a buttered pan until bubbles form",
            "Flip and cook until golden on both sides",
            "Stack and serve with butter and maple syrup",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 380, "protein": "10g", "carbs": "56g", "fat": "14g"},
        "sustainability_tip": "Batter can be halved easily to avoid making more than you'll eat",
        "diet_tags": ["Vegetarian"],
        "cuisine": "American",
    },
    # --- Mexican ---
    {
        "name": "Chicken Fajitas",
        "ingredients": ["chicken breast", "bell pepper", "onion", "tortilla", "lime"],
        "steps": [
            "Slice chicken, bell pepper and onion into strips",
            "Season chicken with fajita spices",
            "Stir-fry chicken until cooked through, then set aside",
            "Stir-fry the peppers and onion until just tender",
            "Combine everything, squeeze over lime and serve with warm tortillas",
        ],
        "prep_time": "15 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 380, "protein": "30g", "carbs": "28g", "fat": "14g"},
        "sustainability_tip": "Odd-shaped peppers work just as well here as perfect ones",
        "diet_tags": ["High Protein", "Halal"],
        "cuisine": "Mexican",
    },
    {
        "name": "Guacamole",
        "ingredients": ["avocado", "tomato", "onion", "lime", "cilantro"],
        "steps": [
            "Mash the avocado in a bowl to the desired texture",
            "Finely dice tomato and onion and stir in",
            "Add chopped cilantro and a squeeze of lime juice",
            "Season with salt to taste",
            "Serve immediately with tortilla chips",
        ],
        "prep_time": "10 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 160, "protein": "2g", "carbs": "10g", "fat": "14g"},
        "sustainability_tip": "Keep the avocado pit in the bowl to help slow browning of leftovers",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Mexican",
    },
    {
        "name": "Beef Burrito",
        "ingredients": ["ground beef", "rice", "beans", "tortilla", "cheese"],
        "steps": [
            "Brown the ground beef with taco seasoning",
            "Warm the rice and beans",
            "Lay a tortilla flat and layer beef, rice, beans and cheese",
            "Fold in the sides and roll tightly",
            "Warm in a dry pan seam-side down until sealed and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 520, "protein": "28g", "carbs": "54g", "fat": "20g"},
        "sustainability_tip": "Leftover rice and beans from another meal work perfectly here",
        "diet_tags": ["High Protein"],
        "cuisine": "Mexican",
    },
    {
        "name": "Mexican Rice",
        "ingredients": ["rice", "tomato", "onion", "garlic", "cumin"],
        "steps": [
            "Toast rice in a little oil until lightly golden",
            "Add onion and garlic, cook until fragrant",
            "Stir in chopped tomato and cumin",
            "Add stock and simmer covered until rice is tender",
            "Fluff with a fork and serve as a side",
        ],
        "prep_time": "10 min",
        "cook_time": "25 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "5g", "carbs": "52g", "fat": "4g"},
        "sustainability_tip": "Very ripe tomatoes blend smoothly into the rice for extra flavor",
        "diet_tags": ["Vegan", "Vegetarian", "Gluten-Free"],
        "cuisine": "Mexican",
    },
    {
        "name": "Black Bean Soup",
        "ingredients": ["black beans", "onion", "garlic", "tomato", "cumin"],
        "steps": [
            "Saute onion and garlic until soft",
            "Add cumin and chopped tomato, cook briefly",
            "Add black beans and stock, bring to a simmer",
            "Blend partially for a creamy but chunky texture",
            "Season and serve with a squeeze of lime",
        ],
        "prep_time": "10 min",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "14g", "carbs": "42g", "fat": "4g"},
        "sustainability_tip": "Dried or canned beans are a low-carbon, affordable protein source",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Mexican",
    },
    # --- Malaysian / Southeast Asian ---
    {
        "name": "Nasi Lemak",
        "ingredients": ["rice", "coconut milk", "egg", "cucumber", "peanut", "anchovy", "sambal"],
        "steps": [
            "Cook rice with coconut milk, pandan leaf and salt until fragrant",
            "Fry the anchovies until crisp",
            "Hard boil or fry the egg",
            "Slice cucumber",
            "Plate the rice with egg, cucumber, anchovies, peanuts and a spoon of sambal",
        ],
        "prep_time": "15 min",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 480, "protein": "14g", "carbs": "58g", "fat": "22g"},
        "sustainability_tip": "Malaysia's national dish — cook only the rice you'll eat to avoid waste",
        "diet_tags": ["Halal"],
        "cuisine": "Malaysian",
    },
    {
        "name": "Chicken Rendang",
        "ingredients": ["chicken thigh", "coconut milk", "lemongrass", "chili", "garlic", "ginger"],
        "steps": [
            "Blend chili, garlic, ginger and lemongrass into a paste",
            "Fry the paste until fragrant and oil separates",
            "Add chicken and coat well in the paste",
            "Pour in coconut milk and simmer, stirring occasionally",
            "Cook low and slow until the sauce is thick and dark, then serve with rice",
        ],
        "prep_time": "20 min",
        "cook_time": "45 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 460, "protein": "28g", "carbs": "12g", "fat": "34g"},
        "sustainability_tip": "Rendang keeps and reheats well — cook a larger batch to save energy later",
        "diet_tags": ["Halal", "Gluten-Free"],
        "cuisine": "Malaysian",
    },
    {
        "name": "Mee Goreng",
        "ingredients": ["noodles", "egg", "bean sprouts", "tofu", "soy sauce", "chili"],
        "steps": [
            "Fry tofu cubes until golden and set aside",
            "Scramble the egg in a hot wok and set aside",
            "Stir-fry noodles with chili and soy sauce",
            "Add bean sprouts and toss briefly",
            "Return tofu and egg to the wok, mix through and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "12 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 400, "protein": "16g", "carbs": "56g", "fat": "14g"},
        "sustainability_tip": "A popular hawker-style dish that's flexible with whatever vegetables you have",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Malaysian",
    },
    {
        "name": "Char Kway Teow",
        "ingredients": ["rice noodles", "egg", "bean sprouts", "shrimp", "soy sauce", "chili"],
        "steps": [
            "Heat a wok until very hot and add oil",
            "Stir-fry shrimp until just pink, set aside",
            "Push noodles into the wok with soy sauce and chili, toss well",
            "Push noodles aside and scramble the egg in the space",
            "Add bean sprouts and shrimp back in, toss everything together and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "12 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 420, "protein": "18g", "carbs": "58g", "fat": "14g"},
        "sustainability_tip": "High wok heat cooks quickly, using less energy than slow simmering",
        "diet_tags": ["Pescatarian"],
        "cuisine": "Malaysian",
    },
    {
        "name": "Laksa",
        "ingredients": ["rice noodles", "coconut milk", "shrimp", "tofu", "chili", "bean sprouts"],
        "steps": [
            "Fry laksa paste (chili, garlic, lemongrass) until fragrant",
            "Add coconut milk and stock, bring to a simmer",
            "Add shrimp and tofu, cook until shrimp is pink",
            "Cook rice noodles separately and place in bowls",
            "Ladle the soup over the noodles and top with bean sprouts",
        ],
        "prep_time": "15 min",
        "cook_time": "20 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 440, "protein": "20g", "carbs": "46g", "fat": "22g"},
        "sustainability_tip": "Make a big pot and freeze the broth base in portions for later",
        "diet_tags": ["Pescatarian", "Gluten-Free"],
        "cuisine": "Malaysian",
    },
    {
        "name": "Satay Chicken",
        "ingredients": ["chicken breast", "peanut", "soy sauce", "turmeric", "lemongrass"],
        "steps": [
            "Cut chicken into strips and thread onto skewers",
            "Marinate in turmeric, lemongrass and soy sauce",
            "Grill skewers over high heat until charred and cooked through",
            "Blend peanuts with soy sauce and a little water for the peanut sauce",
            "Serve skewers with the peanut sauce and sliced cucumber",
        ],
        "prep_time": "20 min",
        "cook_time": "12 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 380, "protein": "32g", "carbs": "12g", "fat": "22g"},
        "sustainability_tip": "Soak wooden skewers in water and reuse metal ones to cut down on waste",
        "diet_tags": ["Halal", "Gluten-Free"],
        "cuisine": "Malaysian",
    },
    {
        "name": "Roti Canai",
        "ingredients": ["flour", "butter", "salt"],
        "steps": [
            "Knead flour, salt and water into a soft dough",
            "Coat the dough in butter and rest for at least 30 minutes",
            "Stretch the dough as thin as possible",
            "Fold into a square and rest briefly",
            "Fry on a hot flat griddle until golden and flaky on both sides",
        ],
        "prep_time": "15 min",
        "cook_time": "10 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 300, "protein": "6g", "carbs": "38g", "fat": "14g"},
        "sustainability_tip": "Make a larger batch and freeze unfried dough balls to reduce future cooking energy",
        "diet_tags": ["Vegetarian"],
        "cuisine": "Malaysian",
    },
    {
        "name": "Vegetable Curry Puff",
        "ingredients": ["potato", "curry powder", "onion", "flour", "peas"],
        "steps": [
            "Cook diced potato and peas with curry powder and onion until fragrant",
            "Make or use ready pastry dough, cut into circles",
            "Spoon filling onto each circle and fold into a half-moon, sealing the edges",
            "Fry until golden and crisp, or bake at 200C for 20 minutes",
            "Serve warm as a snack",
        ],
        "prep_time": "20 min",
        "cook_time": "20 min",
        "difficulty": "Medium",
        "nutrition": {"calories": 280, "protein": "5g", "carbs": "36g", "fat": "12g"},
        "sustainability_tip": "Baking instead of deep-frying uses less oil and energy",
        "diet_tags": ["Vegan", "Vegetarian"],
        "cuisine": "Malaysian",
    },
    # --- Vegan / Vegetarian ---
    {
        "name": "Vegan Buddha Bowl",
        "ingredients": ["quinoa", "chickpeas", "spinach", "avocado", "carrot"],
        "steps": [
            "Cook quinoa according to packet instructions",
            "Roast chickpeas with a little oil and spice until crisp",
            "Shred carrot and wash spinach",
            "Arrange quinoa, chickpeas, spinach and carrot in a bowl",
            "Top with sliced avocado and a simple lemon dressing",
        ],
        "prep_time": "15 min",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 420, "protein": "16g", "carbs": "52g", "fat": "18g"},
        "sustainability_tip": "A plant-based bowl like this has a much smaller carbon footprint than a meat-based meal",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Western",
    },
    {
        "name": "Vegan Lentil Curry",
        "ingredients": ["lentils", "coconut milk", "onion", "garlic", "curry powder", "spinach"],
        "steps": [
            "Saute onion and garlic until soft",
            "Add curry powder and cook until fragrant",
            "Add lentils, coconut milk and water, simmer until lentils are tender",
            "Stir in spinach until wilted",
            "Season and serve with rice",
        ],
        "prep_time": "10 min",
        "cook_time": "25 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 340, "protein": "16g", "carbs": "38g", "fat": "14g"},
        "sustainability_tip": "Lentils and coconut milk together make a filling, low-carbon protein source",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Indian",
    },
    {
        "name": "Tofu Stir Fry",
        "ingredients": ["tofu", "broccoli", "carrot", "soy sauce", "garlic"],
        "steps": [
            "Press and cube the tofu, then pan-fry until golden on all sides",
            "Set tofu aside and stir-fry garlic until fragrant",
            "Add broccoli and carrot, stir-fry until crisp-tender",
            "Return tofu to the pan and add soy sauce",
            "Toss everything together and serve with rice",
        ],
        "prep_time": "10 min",
        "cook_time": "12 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "16g", "carbs": "18g", "fat": "14g"},
        "sustainability_tip": "Tofu has a fraction of the water and carbon footprint of meat proteins",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Asian",
    },
    {
        "name": "Vegan Banana Oat Pancakes",
        "ingredients": ["banana", "oats", "milk", "baking powder"],
        "steps": [
            "Blend oats into a coarse flour",
            "Mash banana and mix with plant milk",
            "Combine with the oat flour and baking powder into a batter",
            "Cook spoonfuls in a lightly oiled pan until bubbles form, then flip",
            "Cook until golden on both sides and serve",
        ],
        "prep_time": "10 min",
        "cook_time": "12 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 260, "protein": "7g", "carbs": "48g", "fat": "5g"},
        "sustainability_tip": "Overripe bananas are ideal here and would otherwise go to waste",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy"],
        "cuisine": "Western",
    },
    {
        "name": "Quinoa Salad",
        "ingredients": ["quinoa", "cucumber", "tomato", "lemon", "olive oil"],
        "steps": [
            "Cook quinoa and let it cool",
            "Dice cucumber and tomato",
            "Combine quinoa with the vegetables in a bowl",
            "Dress with olive oil, lemon juice, salt and pepper",
            "Toss and serve chilled or at room temperature",
        ],
        "prep_time": "15 min",
        "cook_time": "0 min",
        "difficulty": "Easy",
        "nutrition": {"calories": 300, "protein": "9g", "carbs": "40g", "fat": "12g"},
        "sustainability_tip": "Quinoa is a complete plant protein with a lower environmental footprint than meat",
        "diet_tags": ["Vegan", "Vegetarian", "Healthy", "Gluten-Free"],
        "cuisine": "Western",
    },
]


def build_index(recipes):
    index = {}
    for i, recipe in enumerate(recipes):
        for ingredient in recipe["ingredients"]:
            index.setdefault(ingredient, []).append(i)
    return index


def main():
    for i, recipe in enumerate(RECIPES, start=1):
        recipe["id"] = i

    assert len(RECIPES) >= 50, f"Need at least 50 recipes, have {len(RECIPES)}"

    required_keys = {
        "id", "name", "ingredients", "steps", "prep_time", "cook_time",
        "difficulty", "nutrition", "sustainability_tip", "diet_tags", "cuisine",
    }
    for recipe in RECIPES:
        missing = required_keys - recipe.keys()
        assert not missing, f"{recipe['name']} missing keys: {missing}"

    data = {
        "recipes": RECIPES,
        "index": build_index(RECIPES),
    }

    out_dir = os.path.join(os.path.dirname(__file__), "..", "data")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "recipes_full.json")

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Wrote {len(RECIPES)} recipes to {out_path}")


if __name__ == "__main__":
    main()
